Numpy : Practice Problem

1. Extract all odd numbers from arr


In [1]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


<IPython.core.display.Javascript object>

In [2]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

2. Replace all odd numbers in arr with -1

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<IPython.core.display.Javascript object>

In [4]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3. Convert a 1D array to a 2D array with 2 rows

In [7]:
arr=np.arange(10)


<IPython.core.display.Javascript object>

In [8]:
arr.reshape(2, -1) 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4. Stack arrays a and b vertically

In [9]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [10]:
np.concatenate([a, b], axis=0)


<IPython.core.display.Javascript object>

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.vstack([a, b])


<IPython.core.display.Javascript object>

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

5. Get all items between 5 and 10 from a

In [12]:
a = np.array([2, 6, 1, 9, 10, 3, 27])


<IPython.core.display.Javascript object>

Desired Output:
(array([6, 9, 10]),)

In [13]:
a[(a >= 5) & (a <= 10)]


array([ 6,  9, 10])

6. Create a null vector of size 10 but the fifth value which is 1.

In [14]:
ten_zeroes = np.zeros(10)
ten_zeroes[4] = 1
print(ten_zeroes)


<IPython.core.display.Javascript object>

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49.

In [15]:
ten_fortynine = np.arange(10,50)
print(ten_fortynine)

<IPython.core.display.Javascript object>

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Create a 10x10 array with random values and find the minimum and maximum values.

In [21]:
np.random.seed(7)

# low =0
# high = 100
# size = (10,100)

x= np.random.randint(0,100,(10,10))
x.min()

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

0

9. Create a 3*3 matrix and print it's transpose matrix

10. Create two arrays of 2-D and find dot product of it.

11. Compute the maximum for each row in the given array.

In [18]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [20]:
np.max(a, axis=1)


<IPython.core.display.Javascript object>

array([9, 8, 6, 3, 9])

12. Select 3rd & 5th row and 3rd & 4th columns

In [22]:
data = np.random.randint(10,100,(5,4))
data

<IPython.core.display.Javascript object>

array([[25, 69, 45, 58],
       [14, 53, 82, 64],
       [53, 97, 87, 60],
       [49, 13, 39, 22],
       [86, 89, 39, 18]])

In [24]:
data[[2,4],2:4]


array([[87, 60],
       [39, 18]])

13. Convert below matrix into vector

In [25]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

<IPython.core.display.Javascript object>

In [26]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

14. The product of two inverse matrix is identical matrix,prove

In [27]:
# create a square matrix
m = np.array([[2,3],
              [2,4]])

<IPython.core.display.Javascript object>

In [28]:
n=np.linalg.inv(m)

<IPython.core.display.Javascript object>

In [29]:
m.dot(n)

array([[1., 0.],
       [0., 1.]])

15. Create a matrix from a uniform distribution over [0, 1)

In [30]:
mat1 = np.random.rand(2,3)
print ('matrix generated from numpy.random.rand is \n%s\n'%mat1)



<IPython.core.display.Javascript object>

matrix generated from numpy.random.rand is 
[[0.09559835 0.79889497 0.40238848]
 [0.68245195 0.50192349 0.39717781]]

